# Generated by Django 3.1.14 on 2023-09-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('is_published', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], default=0)),
                ('author', models.CharField(max_length=50)),
                ('intro', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
